export const Staff = {

    emp_date: '',
      trn:'',
      nis:'',
      gov_id:'',
      dob:'',
      title:'',
      fname: '',
      lname: '',
      middle_name:'',
      gender:'',
      prev_name:'',
      address1:'',
      address2:'',
      city:'',
      address_duration_month:'',
      address_duration_year:'',
      homephone:'',
      cellphone:'',
      email:'',
      status:'',
      martial_status:'',
      height:'',
      weight:'',
      emergency_name:'',
      emergency_address1:'',
      emergency_address2:'',
      emergency_relationship:'',
      emergency_homephone:'',
      emergency_cellphone:'',
      emergency_email:'',
      family_childnum:'',
      family_child_name1:'',
      family_child_dob1:'',
      family_child_gender1:'',
      family_child_name2:'',
      family_child_dob2:'',
      family_child_gender2:'',
      family_child_name3:'',
      family_child_dob3:'',
      family_child_gender3:'',
      family_child_name4:'',
      family_child_dob4:'',
      family_child_gender4:'',
      family_child_name5:'',
      family_child_dob5:'',
      family_child_gender5:'',
      family_spouse_type:'',
      family_spouse_name:'',
      family_spouse_address1:'',
      family_spouse_address2:'',
      family_homephone:'',
      family_cellphone:'',
      family_email:'',

      edu_institution1:'',
      edu_institution_location1:'',
      edu_qualification1:'',
      edu_year_graduated1:'',

      edu_institution2:'',
      edu_institution_location2:'',
      edu_qualification2:'',
      edu_year_graduated2:'',

      edu_institution3:'',
      edu_institution_location3:'',
      edu_qualification3:'',
      edu_year_graduated3:'',

      edu_institution4:'',
      edu_institution_location4:'',
      edu_qualification4:'',
      edu_year_graduated4:'',

      training_institution1:'',
      training_location1:'',
      training_certification1:'',
      training_year_graduated1:'',

      training_institution2:'',
      training_location2:'',
      training_certification2:'',
      training_year_graduated2:'',

      training_institution3:'',
      training_location3:'',
      training_certification3:'',
      training_year_graduated3:'',

      training_institution4:'',
      training_location4:'',
      training_certification4:'',
      training_year_graduated4:'',

      training_institution5:'',
      training_location5:'',
      training_certification5:'',
      training_year_graduated5:'',

      cok_relatives_name1:'',
      cok_relatives_branch1:'',
      cok_relatives_relation1:'',

      cok_relatives_name2:'',
      cok_relatives_branch2:'',
      cok_relatives_relation2:'',

      cok_relatives_name3:'',
      cok_relatives_branch3:'',
      cok_relatives_relation3:'',

      cok_relatives_name4:'',
      cok_relatives_branch4:'',
      cok_relatives_relation4:'',

      cok_relatives_name5:'',
      cok_relatives_branch5:'',
      cok_relatives_relation5:'',
      pep_check:'',
      pep_persons:'',
      charity_chech:'',
      charity_persons:'',

      banking_institution1:'',
      banking_account_type1:'',
      banking_joint_holder1:'',
      banking_account_balance1:'',

      banking_institution2:'',
      banking_account_type2:'',
      banking_joint_holder2:'',
      banking_account_balance2:'',

      banking_institution3:'',
      banking_account_type3:'',
      banking_joint_holder3:'',
      banking_account_balance3:'',

      banking_institution4:'',
      banking_account_type4:'',
      banking_joint_holder4:'',
      banking_account_balance4:'',

      guarantor_check:'',
      guarantor_details:'',

      guarantor_poa:'',

      guarantor_poa_institution1:'',
      guarantor_poa_branch1:'',
      guarantor_poa_account_type1:'',
      guarantor_poa_joint_holder1:'',

      guarantor_poa_institution2:'',
      guarantor_poa_branch2:'',
      guarantor_poa_account_type2:'',
      guarantor_poa_joint_holder2:'',

      guarantor_poa_institution3:'',
      guarantor_poa_branch3:'',
      guarantor_poa_account_type3:'',
      guarantor_poa_joint_holder3:'',
    
    }


